# Generated by Django 5.1 on 2024-08-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0002_remove_author_email_remove_author_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.CharField(choices=[('ktm', 'Kathmandu'), ('lat', 'Lalitpur'), ('bat', 'Bhaktapur')], default='ktm', max_length=40),
        ),
        migrations.AlterField(
            model_name='reader',
            name='address',
            field=models.CharField(choices=[('ktm', 'Kathmandu'), ('lat', 'Lalitpur'), ('bat', 'Bhaktapur')], default='ktm', max_length=40),
        ),
    ]
