# Generated by Django 5.1 on 2024-08-11 11:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0003_author_email_reader_email_alter_author_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.CreateModel(
            name='PostAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='userpost.reader')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='userpost.post')),
            ],
        ),
    ]
