# Generated by Django 5.1 on 2024-08-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0005_remove_postanalysis_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanalysis',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='Rating'),
        ),
    ]
