# Generated by Django 5.1 on 2024-08-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0006_alter_postanalysis_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
